-- QUESTIONS: Supabase database setup
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.questions_responses (
  id bigint generated by default as identity primary key,
  answer text not null check (answer in ('yes','think','no')),
  visitor_id uuid,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.questions_responses enable row level security;

-- Anyone with the public website can submit an answer.
drop policy if exists "Public can submit answers" on public.questions_responses;
create policy "Public can submit answers"
on public.questions_responses
for insert
to anon
with check (answer in ('yes','think','no'));

-- Only signed-in users can read answers.
drop policy if exists "Signed in user can read answers" on public.questions_responses;
create policy "Signed in user can read answers"
on public.questions_responses
for select
to authenticated
using (true);

-- Optional: prevent anonymous users from reading anything.
drop policy if exists "No anonymous reads" on public.questions_responses;

grant insert on public.questions_responses to anon;
grant select on public.questions_responses to authenticated;
